version: '3.8'

services:
  trendstore:
    image: ajaykumar91/trendstore:latest
    container_name: trendstore-container
    ports:
      - "3000:80"
    restart: always
    networks:
      - trend-network

networks:
  trend-network:
    driver: bridge