apiVersion: v1
kind: Service
metadata:
  name: trendstore-service
  namespace: trendstore-ns
spec:
  type: LoadBalancer
  selector:
    app: trendstore
  ports:
    - protocol: TCP
      port: 80 # k8s port
      targetPort: 80 # hostPort in the container