apiVersion: v1
kind: Service
metadata:
  name: trendstore-service

spec:
  type: LoadBalancer
  selector:
    app: trendstore-label
  ports:
    - protocol: TCP
      port: 80 # k8s port
      targetPort: 80 # hostPort in the container
      